baseURL: "https://habet.dev"
languageCode: "en-us"
title: "Abe's Portfolio"
theme: "./.."
relativeURLs: true

googleanalytics: UA-216916075-1
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true

# menus
Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /ew
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /34545
    #   parent: dropdown
    #   weight: 2

params:
  version: 3
  customCSS: false

  favicon: "/images/fav.png"
  description: "Abe's personal portfolio and blog."
  images:
    - "/images/site-feature-image.jpg"

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Abe"
  namecolor: ffc107
  profession: "Sofware Engineer"
  github: "https://github.com/abe-101"
    #gitlab: "https://gitlab.com/abe-101"
  linkedin: "https://linkedin.com/in/abe101"
  twitter: "https://twitter.com/habet_dot_dev"
    #instagram: "https://instagram.com/"
    #facebook: "https://facebook.com"

  # Custom social links
  customSocialLinks:
    - fontAwesomeIconName: "fab fa-reddit"
      url: "https://www.reddit.com/user/abe-101/"
    - fontAwesomeIconName: "fab fa-tumblr"
      url: "https://abe-101.tumblr.com/"
    - fontAwesomeIconName: "fab fa-hacker-news"
      url: "https://news.ycombinator.com/user?id=abe-101"
    - fontAwesomeIconName: "fa fa-envelope"
      url: "mailto:admin@habet.dev"


  # About
  disable_about: false
  aliases:
    - /about/
  descripe_l1_person: "I'm Abe"
  descripe_l2_person: "A software engineer and open source enthusiast.
I love building delightful developer experiences."
  skills:
    - name: Python
      percentage: 70
    - name: C
      percentage: 85
    - name: SQL
      percentage: 70
    - name: Smile
      percentage: 100

  # Experience
  disable_experience: true
  experience:
    - company: "Google"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Software developer"
      startdate: Feb 2021
      enddate: present
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Facebook"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Amazon"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: true
  education:
    - degree: "B.tech"
      branch: "Information Technology"
      university: "Example university"
      startedyear: "2013"
      graduation: "2018"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"

  # Projects
  disable_projects: false
  projects:
    # - name: 
    #   img: 
    #   githublink: 
    #   featuredlink: 
    #   description: 

  # Achievements
  disable_achievements: true
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "abe@habet.dev"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
